apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mfndyngn5-python-gitops
  description: This is GitOps manifest for mfndyngn5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: mfndyngn5-python
    backstage.io/kubernetes-id: mfndyngn5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: mfndyngn5-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mfndyngn5-python
